version: "3.7"

services:

  database_rentcar: 
    image: postgres
    container_name: database_rentcar
    restart: always
    ports:
      - 5000:5432
    environment: 
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentcar
    volumes:
     - pgdata:/data/postgres
    # networks:
    #   - my-network
    
  # app:
  #   build: .
  #   container_name: rentcar
  #   ports:
  #     - 3333:3333
  #   volumes:
  #     - .:/usr/appNode
  #   # networks:
  #   #   - my-network
  #   links:
  #     - database_rentcar
  #   depends_on:
  #     - database_rentcar

volumes:
  pgdata:
    driver: local

# networks:
#   my-network:
#     driver: bridge